name: bankly_task
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_svg: ^0.17.1
  percent_indicator: ^2.1.1+1
  provider: ^4.0.2
  url_launcher: ^5.4.1
  hive: ^1.3.0
  hive_flutter: ^0.3.0+1
#  moor: ^2.2.0
#  moor_ffi: ^0.3.1
  flutter_icons: ^1.0.0+1
  shared_preferences: ^0.5.6+1
  shimmer: ^1.0.1
#  animated_text_kit: ^2.0.0
  esys_flutter_share: ^1.0.2
  webview_flutter: ^0.3.19+5
  cached_network_image: ^2.0.0
  page_transition: ^1.1.5
#  commons: ^0.6.3
  uuid: ^2.0.4
  intl: ^0.16.1
  connectivity: ^0.4.5+1
#  connectivity: ^0.3.2
  fluttertoast: ^3.1.3
  hive_generator: ^0.7.0
  build_runner: ^1.7.3
  moor_generator: ^2.2.0
  # Auto resize text widget
#  auto_size_text: ^2.1.0
  # Avoid keyboard from overlapping text fields
#  keyboard_avoider: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/onboarding0.png
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/one.jpg
    - assets/images/middlemessy.jpg
    - assets/images/messymiddle.png
    - assets/images/three.jpg
    - assets/images/four.jpg
    - assets/facebook.png
      # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware.


  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Black.ttf
    - family: Montserrat
      fonts:
        - asset: assets/Montserrat-Regular.ttf
        - asset: assets/Montserrat-Bold.ttf
          weight: 700
